# ./roles/proxmox_mount_nfs/tasks/main.yml

- name: Ensure NFS packages are installed (Debian-based)
  apt:
    name: nfs-common
    state: present

- name: Ensure NFS mount directory exists
  ansible.builtin.file:
    path: "{{ (nfs_mount | selectattr('src', 'equalto', nfs_mount_selection) | first).dest }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Mount NFS share and add to fstab
  ansible.builtin.mount:
    src: "{{ (nfs_mount | selectattr('src', 'equalto', nfs_mount_selection) | first).src }}"
    path: "{{ (nfs_mount | selectattr('src', 'equalto', nfs_mount_selection) | first).dest }}"
    fstype: "{{ (nfs_mount | selectattr('src', 'equalto', nfs_mount_selection) | first).fstype | default('nfs') }}"
    opts: "{{ nfs_mount_options }}"
    state: mounted

