# File: playbooks/lala115-docker-host-deploy-paperless.yml
---
- name: Deploy Paperless-NGX Docker Container
  hosts: lala115
  become: true
  vars_files:
    - ../vault/vault.yml
  vars:
    app_key: paperless-ngx
    paperless_config_dir: "/home/admin/paperless-ngx"
    paperless_data_dir: "/mnt/paperless-ngx"
    file_owner: "{{ docker_config.owner | default('admin') }}"
    file_group: "{{ docker_config.group | default('admin') }}"
    file_mode: "{{ docker_config.mode | default('0755') }}"
    env_file_mode: "{{ docker_config.env_mode | default('0600') }}"
  tasks:
    - name: Ensure Docker is installed
      apt:
        name:
          - docker.io
          - docker-compose-plugin  # Install the docker compose plugin for V2
        state: present
        
    - name: Create Paperless config directory if it doesn't exist
      file:
        path: "{{ paperless_config_dir }}"
        state: directory
        owner: "{{ file_owner }}"
        group: "{{ file_group }}"
        mode: "{{ file_mode }}"

    - name: Copy docker-compose.yml file
      copy:
        src: ../files/paperless-docker-compose.yml
        dest: "{{ paperless_config_dir }}/docker-compose.yml"
        owner: "{{ file_owner }}"
        group: "{{ file_group }}"
        mode: "{{ file_mode }}"

    - name: Create .env file from template
      template:
        src: ../templates/paperless.env.j2
        dest: "{{ paperless_config_dir }}/.env"
        owner: "{{ file_owner }}"
        group: "{{ file_group }}"
        mode: "{{ env_file_mode }}"

    - name: Deploy Paperless-NGX using docker compose v2
      community.docker.docker_compose_v2:
        project_src: "{{ paperless_config_dir }}"
        files:
          - docker-compose.yml
        state: present
        pull: "missing"
      register: compose_result