---
- name: Deploy VMs from inventory
  hosts: lala100
  become: true
  gather_facts: false

  vars_files:
    - ../vault/vault.yml

  tasks:
    - name: Loop over virtual machines
      include_role:
        name: proxmox_cloud_vm
      loop: "{{ virtual_machines | dict2items }}"
      loop_control:
        label: "{{ item.key }}"
      vars:
        vm_config: "{{ item.value }}"
